# Generated by Django 4.0.4 on 2022-06-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('application', models.CharField(blank=True, max_length=100)),
                ('urls', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
