# Generated by Django 2.2.24 on 2022-06-16 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0003_auto_20220607_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='app',
            name='user',
        ),
    ]
